---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv
  labels:
    type: local
    name: sharedvolume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    #path: "/tmp"
    path: "/mnt/sharedfolder"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: sharedvolume
© 2020 GitHub, Inc.
